### ISSUE TITLE
Revise ball direction and speed at new game start

### ISSUE THREAD

**Issue by 2j1j5** [JohannesFriedrich/Pong4four#2]
current codes causes ball to start on straight line at random occurrence and with different speed

**Comment by 2j1j5** [comment]
proposed a few changes in pull request #3 
changes were primarily made to the main program loop, was not able to test it yet :-/

**Comment by 2j1j5** [comment]
merge from pull request #3 works in basic functionality, but
ball can still start in strictly vertical/horizontal direction -> subject to further revision

**Comment by JohannesFriedrich** [comment]
done with 454a07b837fbf258ce6b0e577f94ac992f620758.
-> Close
